## Vendra Support

The `misaf/vendra-support` package owns the shared support layer for every Vendra module — most importantly the **tenant-awareness abstraction** that all other modules derive from.

### Translatable Persistence

- Making a persisted model field translatable is an explicit domain choice unless this package already requires it.
- Every field listed in a model's `$translatable` array must definitely use a JSON database column. Keep its model traits/casts, factories, validation, Filament locale UI, API serialization, and tests translation-aware.
- A field not listed in `$translatable` must use the appropriate scalar database type and must not use Spatie Translatable, translatable slug traits, locale switchers, translated callbacks, or translation-shaped array data.

### Vendra Transitive API Policy

- Treat a Vendra dependency intentionally exposed through the public API of a directly required Vendra platform package as part of the supported public contract of that package.
- Do not add a redundant direct Composer requirement solely because source code imports a type from that exposed dependency.
- Apply this only to Vendra platform packages listed under `require`; never extend it to `require-dev`, `suggest`, incidental implementation dependencies, or third-party packages. Removing or replacing an exposed dependency is a breaking change; keep `self.version` alignment across the Vendra package graph.

- Keep shared support code inside `packages/vendra-support` using the `Misaf\VendraSupport` namespace.
- This package owns the tenant contract and defaults: `Contracts\TenantResolver`, the default `NullTenantResolver` binding, `Support\TenantAwareness`, `Traits\BelongsToTenant`, `Scopes\TenantScope` / `TeamScope`, `Support\TenantSchema`, `Concerns\RequiresCurrentTenant`, `Support\TenantSeeders`, the base `Database\Seeders` (`DemoContentSeeder`, `PermissionPolicySeeder`), the base `Console\Commands` (`SeedCommand`, `TenantSeedCommand`), shared `Filament\Concerns`, and shared events/listeners.
- Modules register their seed command class with `TenantSeeders::register(SeedCommand::class, priority: …)`; `Tenancy\Listeners\RunTenantSeeders` runs each command's static `seeders()` directly inside the provisioned tenant (restoring the previous one), never through `Artisan::call`, so every `SeedCommand` is registered console-only with `hasConsoleCommand()`.
- This package also owns optional capability contracts and null defaults, including `TagResolver`, `TagIntegration`, `TagRelationship`, and `SubscriptionCharger` (null default `NullSubscriptionCharger`, `available()` false — a payment provider such as one backed by `misaf/vendra-transaction` binds the real charger). Domain consumers use these without importing the concrete provider package. `SubscriptionCharge::reference` is an idempotency key: repeated identical calls to `charge()` or `retrieve()` must resolve to the same provider operation without collecting twice, and reuse for different details must be rejected. Results use `SubscriptionChargeResult` and `SubscriptionChargeStatus`; a timeout or processing response is never reported as paid.
- `TenantEntitlements` (null default `NullTenantEntitlements`: everything allowed, nothing limited) answers what the plan behind a tenant allows through the `Enums\PlanFeature` flags and the `Enums\PlanLimit` per-store caps; `misaf/vendra-store` binds the real one. Domain packages register how much of a limit a tenant uses with `Tenancy\TenantUsageRegistry` (counters take the tenant explicitly and drop every global scope) check room with `canAdd()` (to disable UI ahead of time) and guard their writes with `assertCanAdd()`/`assertAllows()`, which throw `Exceptions\EntitlementExceededException` with a translated message panels can show as it is. After a successful add they call `recordAdded()` from a `created` hook, so the bound implementation can warn the reseller as usage nears the limit. `Filament\Widgets\PlanUsageWidget`, discovered on the configured panels, shows the current store its usage of every limited `PlanLimit`, says when the store is over one, and hides itself when nothing is limited. `Tenancy\TenantLimitOverages::exceeded()` lists the limits a tenant already uses more of than its plan allows, which only happens after a plan change or lowered limits. `PlanLimit::StaffPerStore` counts a store's users who hold a role; customers hold none.
- `Context\RequestJobContext` is the provider-neutral value object for request, command, and queued-job observability. Keep only shared trace, actor, operation, tenant, and hidden idempotency identifiers as first-class fields; owning domains add visible metadata through its generic bag. Use `add()` for the current context and `scope()` for temporary context so Laravel propagates it to queued jobs.
- This package owns the shared policy authorization concerns: `Concerns\ResolvesPolicyPermissions` plus the composable `Concerns\Authorizes*Abilities` traits (View, Create, Update, Delete, ForceDelete, Restore, Replicate, Reorder). Domain policies compose whole ability traits, implement `permissionEnum()` returning the module's `*PolicyEnum`, and keep hard denies or model-state rules as explicit methods — never adopt a trait whose abilities the resource does not grant.
- Policy permission enums use TitleCase cases named after the ability (`ViewAny`, `ForceDelete`) with kebab-case permission values (`view-any-attribute`); `ResolvesPolicyPermissions` resolves cases by ability name, so case names must match.
- Keep tag relationship metadata framework-level and provider-neutral. `vendra-tagger` supplies the real resolver; consumers must remain functional with `NullTagResolver`.
- Use `HasOptionalTags` as the single implementation of consumer polymorphic tag relations. Each consumer supplies its own stable type and conditionally renders UI through `TagIntegration`.
- **This is the only place tenant logic lives.** It defines the abstraction and binds `NullTenantResolver` by default (tenancy disabled). A tenant provider (e.g. `misaf/vendra-tenant`) overrides the `TenantResolver` binding to enable it.
- Never reference a concrete tenant provider such as `Misaf\VendraTenant` here. Support must build and run with no provider installed; everything derives from the bound `TenantResolver` and `TenantAwareness::enabled()`. There is no `tenant_aware` config toggle.
- `TenantSchema::addTenantColumn` adds `tenant_id` only when tenancy is enabled; `BelongsToTenant` stamps `tenant_id` on `creating` from the current tenant. Domain providers register their tenant-aware tables with `TenantTableRegistry`, allowing a concrete provider to retrofit schemas that were migrated while tenancy was disabled.
- Shared Filament navigation taxonomy lives in `Misaf\VendraSupport\Filament\Navigation\NavigationGroup`. Keep group labels and ordering there; domain packages must not invent app-level group strings.
- Boolean active/inactive state uses `Filament\Forms\Components\IsActiveToggle` in schemas and `Filament\Tables\Columns\IsActiveToggleColumn` in tables. Both default to the `active` column, the Bolt on-icon, and the shared `vendra-support::attributes.active` label; pass another name (`IsActiveToggle::make('in_stock')`) and chain `->label()` or `->default()` per resource instead of rebuilding `Toggle` / `ToggleColumn` chains. `IsActiveToggleColumn` refuses the inline update unless the panel user may `update` the record under its policy, so never hand-build a `ToggleColumn` that would skip that check.
- Show and filter that state with `Filament\Infolists\Components\IsActiveEntry`, `Filament\Tables\Filters\QueryBuilder\Constraints\IsActiveConstraint`, and `Filament\Tables\Filters\IsActiveFilter` instead of rebuilding `IconEntry`, `BooleanConstraint`, or `TernaryFilter` chains.
- Default-record flags use `Filament\Forms\Components\IsDefaultToggle`, `Filament\Infolists\Components\IsDefaultEntry`, `Filament\Tables\Columns\IsDefaultIconColumn`, `Filament\Tables\Filters\IsDefaultFilter`, and `Filament\Tables\Filters\QueryBuilder\Constraints\IsDefaultConstraint`, labelled from `vendra-support::attributes.is_default`; primary flags use `Filament\Forms\Components\IsPrimaryToggle` and `Filament\Tables\Columns\IsPrimaryIconColumn`, labelled from `vendra-support::attributes.is_primary`. Add `helperText()` or `visible()` at the call site instead of rebuilding the `Toggle` / `IconEntry` / `IconColumn` / `TernaryFilter` / `BooleanConstraint` chains, and never show these booleans as a badge next to the name.
- Keep "one active default" rules in `Observers\Concerns\MaintainsSingleActiveDefault`: an observer uses the trait and adds only its own hooks (see `PlanObserver`'s in-use guard). Never copy the creating/saving/saved/deleted default juggling into a package observer.
- Keep "one flagged row per owner" rules in `Observers\Concerns\MaintainsSingleFlagPerOwner`, whose observer names only `flagColumn()` and `ownerColumn()` (see `AddressObserver`, `PhoneNumberObserver`, `UserProfileObserver`). Use `MaintainsSingleActiveDefault` instead for a tenant-wide default among `active` rows.
- Timestamp and row-number table columns use `Filament\Tables\Columns\CreatedAtColumn`, `UpdatedAtColumn`, `DeletedAtColumn`, and `RowIndexColumn`. The timestamp columns carry the shared label, LTR cell, since-tooltip, and `Y-m-d H:i` format (Jalali when the locale is `fa`); `DeletedAtColumn` also shows `—` while the record is not trashed; `RowIndexColumn` is labelled `#` and sorts by `id`. Chain `->sortable()`, `->badge()`, or `->sortable(['position'])` per table instead of rebuilding the `TextColumn` chains.
- Infolists show timestamps with `Filament\Infolists\Components\CreatedAtEntry`, `UpdatedAtEntry`, and `DateTimeEntry::make('sent_at')->label(...)` for other attributes; do not add a private `dateEntry()` helper. Read-only active columns use `Filament\Tables\Columns\IsActiveIconColumn`, and query builders use `Filament\Tables\Filters\QueryBuilder\Constraints\PositionConstraint`, `NameConstraint`, and `SlugConstraint`.
- Name, slug, and description attributes use `Filament\Forms\Components\SluggableNameInput` (fills `slug` from the name until the slug is edited), `SlugInput`, `DescriptionTextarea`, `Filament\Infolists\Components\NameEntry`, `SlugEntry`, `DescriptionEntry` (`->richContent()` for rich-editor JSON), and `Filament\Tables\Columns\SlugColumn`, all labelled from `vendra-support::attributes.*`. Chain `->uniqueWithinTenant(perLocale: true)` for translatable columns or `->uniqueWithinTenant()` for scalar ones; a resource with extra unique constraints (such as a tag type) calls `->unique()` itself. Length limits, rows, and placeholders stay at the call site.
- Table name and description columns use `Filament\Tables\Columns\NameColumn` and `DescriptionColumn`, and rich-text descriptions use `Filament\Forms\Components\DescriptionRichEditor`; chain `searchable()`, `sortable()`, `state()`, or `live()` per resource instead of rebuilding the chains.
- Store every package resource that declares a `$cluster` under `src/Filament/Clusters/Resources/` with a matching `Filament\Clusters\Resources` namespace. Store resources without a cluster under `src/Filament/Resources/`.
- Keep group priority in this order: Catalog, Sales, Customers, Content, Marketing, Localization, System. Register panel group labels with closures so the request locale is resolved after locale middleware runs.
- Use domain clusters as top-level sidebar items and render their resources as ungrouped, top-positioned sub-navigation tabs so `NavigationPriority` controls the visible order without Filament's grouped-item bucket taking precedence.
- Give every resource one distinct outlined `Heroicon`; navigation group headers remain icon-free.
- Assign every resource a case in `NavigationPriority` and use that case for `$navigationSort`. Keep values globally unique, grouped by domain cluster, and leave gaps for future resources. Update `tests/Feature/AdminNavigationTest.php` whenever adding or moving navigation.
- Give every resource separate singular and plural translation keys in `en`, `de`, and `fa`. Use the singular key for model labels and the plural key for navigation and plural model labels; keep navigation labels at 24 characters or fewer.
- Keep package plugin navigation-group overrides working, but default them to a `vendra-support::navigation.groups.*` key. Resolve breadcrumbs to the package label, not the broad group label.
- Browser-check the sidebar in a non-default locale after navigation changes. Do not register a navigation entry until its destination renders successfully.
- Follow Laravel comment style: document with PHPDoc (array shapes, generics, `@see`) and reserve inline comments for genuinely complex logic.
- Keep Pest architecture tests in `tests/ArchTest.php`: the `php`, `security`, and `laravel` presets plus `arch()->expect('Misaf\VendraSupport')->not->toUse('Misaf\VendraTenant')`.

- Demo seeders declare their factory dependencies in `FACTORIES`; the shared base uses bundled fixtures when any declared factory is unavailable, including standalone Composer installs. Keep factories in development autoloading.
